apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-monitor-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-monitor-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: node-monitor-serviceaccount
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: node-monitor-serviceaccount-secret
  annotations:
    kubernetes.io/service-account.name: node-monitor-serviceaccount
type: kubernetes.io/service-account-token